name = "inconigto"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "SIREN"
id = "a05083cee0c54935b38878aa76e2fff3"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/Inconigto-Mode/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/Inconigto-Mode/refs/heads/master/web/sub.html"

  { pattern = "afrcloud.site", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.site", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.site", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.site", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud.site", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.site", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.site", custom_domain = true },
]
name = "inconigto"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

[[kv_namespaces]]
binding = "SIREN"
id = "a05083cee0c54935b38878aa76e2fff3"
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/Inconigto-Mode/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/Inconigto-Mode/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/InconigtoMode/Inconigto-Mode/refs/heads/master/web/link.html"
