name = "afrcloud-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "*.afrcloud.xyz/*", custom_domain = true },
  { pattern = "*.afrcloud.my.id/*", custom_domain = true },
  { pattern = "*.afrcloud.site/*", custom_domain = true },
  { pattern = "*.afrcloud.web.id/*", custom_domain = true }
]


[[kv_namespaces]]
binding = "SIREN"
id = "bcd06f44fbe0493aa2ec3457c4799444"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/converter.html"
