name = "test"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


[[kv_namespaces]]
binding = "SIREN"
id = "bcd06f44fbe0493aa2ec3457c4799444"

[[kv_namespaces]]
binding = "HTML_FILES"
id = "a2717c696ca343dbb1d98a4d76c1a548"

[[kv_namespaces]]
binding = "CSS_FILES"
id = "5b39658321584606b9128e76913ec421"

[[kv_namespaces]]
binding = "JS_FILES"
id = "1fb5a8787fca4015b00c2f866b915e46"

[[kv_namespaces]]
binding = "IMAGE_FILES"
id = "6a700df87b3542f7b9097112c39651b8"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/converter.html"
