name = "afrcloud-siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true


routes = [
  # Wildcard routes untuk menangani semua subdomain di domain tertentu
  { pattern = "*.afrcloud.xyz/*", zone_name = "afrcloud.xyz" },
  { pattern = "*.afrcloud.my.id/*", zone_name = "afrcloud.my.id" },
  { pattern = "*.afrcloud.site/*", zone_name = "afrcloud.site" },
  { pattern = "*.afrcloud.web.id/*", zone_name = "afrcloud.web.id" },
  { pattern = "afrcloud.xyz", zone_name = "afrcloud.xyz" },
  { pattern = "afrcloud.my.id", zone_name = "afrcloud.my.id" },
  { pattern = "afrcloud.site", zone_name = "afrcloud.site" },
  { pattern = "afrcloud.web.id", zone_name = "afrcloud.web.id" },
  
  # Rute eksplisit untuk custom domains pada domain afrcloud.xyz
  { pattern = "afrcloud.xyz", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.xyz", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.xyz", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.xyz", custom_domain = true },
  { pattern = "help.viu.com.afrcloud.xyz", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.xyz", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.xyz", custom_domain = true },
  { pattern = "graph.facebook.com.afrcloud.xyz", custom_domain = true },
  { pattern = "dogseechew.com.afrcloud.xyz", custom_domain = true },
  { pattern = "oec22-normal-alisg.tokopediax.com.afrcloud.xyz", custom_domain = true },
  { pattern = "investor.fb.com.afrcloud.xyz", custom_domain = true },
  { pattern = "bakrie.ac.id.afrcloud.xyz", custom_domain = true },
  { pattern = "unnes.ac.id.afrcloud.xyz", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.afrcloud.xyz", custom_domain = true },
  { pattern = "instagram.com.afrcloud.xyz", custom_domain = true },
  { pattern = "scorecardresearch.com.afrcloud.xyz", custom_domain = true },
  { pattern = "pubgmobile.com.afrcloud.xyz", custom_domain = true },
  { pattern = "byteoversea.com.afrcloud.xyz", custom_domain = true },
  { pattern = "tokopedia.net.afrcloud.xyz", custom_domain = true },
  { pattern = "tokopedia.com.afrcloud.xyz", custom_domain = true },
  { pattern = "shopee.co.id.afrcloud.xyz", custom_domain = true },
  { pattern = "tiktokcdn.com.afrcloud.xyz", custom_domain = true },
  { pattern = "awsglobalaccelerator.com.afrcloud.xyz", custom_domain = true },
  { pattern = "akamaized.net.afrcloud.xyz", custom_domain = true },
  { pattern = "shopeemobile.com.afrcloud.xyz", custom_domain = true },
  { pattern = "clova.line.me.afrcloud.xyz", custom_domain = true },
  { pattern = "udemy.com.afrcloud.xyz", custom_domain = true },
  { pattern = "ruangguru.com.afrcloud.xyz", custom_domain = true },
  { pattern = "data.mt.afrcloud.xyz", custom_domain = true },

  # Rute eksplisit untuk custom domains pada domain afrcloud.my.id
  { pattern = "afrcloud.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.my.id", custom_domain = true },
  { pattern = "help.viu.com.afrcloud.my.id", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.my.id", custom_domain = true },
  { pattern = "graph.facebook.com.afrcloud.my.id", custom_domain = true },
  { pattern = "dogseechew.com.afrcloud.my.id", custom_domain = true },
  { pattern = "oec22-normal-alisg.tokopediax.com.afrcloud.my.id", custom_domain = true },
  { pattern = "investor.fb.com.afrcloud.my.id", custom_domain = true },
  { pattern = "bakrie.ac.id.afrcloud.my.id", custom_domain = true },
  { pattern = "unnes.ac.id.afrcloud.my.id", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.afrcloud.my.id", custom_domain = true },
  { pattern = "instagram.com.afrcloud.my.id", custom_domain = true },
  { pattern = "scorecardresearch.com.afrcloud.my.id", custom_domain = true },
  { pattern = "pubgmobile.com.afrcloud.my.id", custom_domain = true },
  { pattern = "byteoversea.com.afrcloud.my.id", custom_domain = true },
  { pattern = "tokopedia.net.afrcloud.my.id", custom_domain = true },
  { pattern = "tokopedia.com.afrcloud.my.id", custom_domain = true },
  { pattern = "shopee.co.id.afrcloud.my.id", custom_domain = true },
  { pattern = "tiktokcdn.com.afrcloud.my.id", custom_domain = true },
  { pattern = "awsglobalaccelerator.com.afrcloud.my.id", custom_domain = true },
  { pattern = "akamaized.net.afrcloud.my.id", custom_domain = true },
  { pattern = "shopeemobile.com.afrcloud.my.id", custom_domain = true },
  { pattern = "clova.line.me.afrcloud.my.id", custom_domain = true },
  { pattern = "udemy.com.afrcloud.my.id", custom_domain = true },
  { pattern = "ruangguru.com.afrcloud.my.id", custom_domain = true },
  { pattern = "data.mt.afrcloud.my.id", custom_domain = true },

  # Rute eksplisit untuk custom domains pada domain afrcloud.web.id
  { pattern = "afrcloud.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.web.id", custom_domain = true },
  { pattern = "help.viu.com.afrcloud.web.id", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.web.id", custom_domain = true },
  { pattern = "graph.facebook.com.afrcloud.web.id", custom_domain = true },
  { pattern = "dogseechew.com.afrcloud.web.id", custom_domain = true },
  { pattern = "oec22-normal-alisg.tokopediax.com.afrcloud.web.id", custom_domain = true },
  { pattern = "investor.fb.com.afrcloud.web.id", custom_domain = true },
  { pattern = "bakrie.ac.id.afrcloud.web.id", custom_domain = true },
  { pattern = "unnes.ac.id.afrcloud.web.id", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.afrcloud.web.id", custom_domain = true },
  { pattern = "instagram.com.afrcloud.web.id", custom_domain = true },
  { pattern = "scorecardresearch.com.afrcloud.web.id", custom_domain = true },
  { pattern = "pubgmobile.com.afrcloud.web.id", custom_domain = true },
  { pattern = "byteoversea.com.afrcloud.web.id", custom_domain = true },
  { pattern = "tokopedia.net.afrcloud.web.id", custom_domain = true },
  { pattern = "tokopedia.com.afrcloud.web.id", custom_domain = true },
  { pattern = "shopee.co.id.afrcloud.web.id", custom_domain = true },
  { pattern = "tiktokcdn.com.afrcloud.web.id", custom_domain = true },
  { pattern = "awsglobalaccelerator.com.afrcloud.web.id", custom_domain = true },
  { pattern = "akamaized.net.afrcloud.web.id", custom_domain = true },
  { pattern = "shopeemobile.com.afrcloud.web.id", custom_domain = true },
  { pattern = "clova.line.me.afrcloud.web.id", custom_domain = true },
  { pattern = "udemy.com.afrcloud.web.id", custom_domain = true },
  { pattern = "ruangguru.com.afrcloud.web.id", custom_domain = true },
  { pattern = "data.mt.afrcloud.web.id", custom_domain = true },

  # Rute eksplisit untuk custom domains pada domain afrcloud.site
  { pattern = "afrcloud.site", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.site", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.site", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.site", custom_domain = true },
  { pattern = "help.viu.com.afrcloud.site", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.site", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.site", custom_domain = true },
  { pattern = "graph.facebook.com.afrcloud.site", custom_domain = true },
  { pattern = "dogseechew.com.afrcloud.site", custom_domain = true },
  { pattern = "oec22-normal-alisg.tokopediax.com.afrcloud.site", custom_domain = true },
  { pattern = "investor.fb.com.afrcloud.site", custom_domain = true },
  { pattern = "bakrie.ac.id.afrcloud.site", custom_domain = true },
  { pattern = "unnes.ac.id.afrcloud.site", custom_domain = true },
  { pattern = "customlinks.appsflyer.com.afrcloud.site", custom_domain = true },
  { pattern = "instagram.com.afrcloud.site", custom_domain = true },
  { pattern = "scorecardresearch.com.afrcloud.site", custom_domain = true },
  { pattern = "pubgmobile.com.afrcloud.site", custom_domain = true },
  { pattern = "byteoversea.com.afrcloud.site", custom_domain = true },
  { pattern = "tokopedia.net.afrcloud.site", custom_domain = true },
  { pattern = "tokopedia.com.afrcloud.site", custom_domain = true },
  { pattern = "shopee.co.id.afrcloud.site", custom_domain = true },
  { pattern = "tiktokcdn.com.afrcloud.site", custom_domain = true },
  { pattern = "awsglobalaccelerator.com.afrcloud.site", custom_domain = true },
  { pattern = "akamaized.net.afrcloud.site", custom_domain = true },
  { pattern = "shopeemobile.com.afrcloud.site", custom_domain = true },
  { pattern = "clova.line.me.afrcloud.site", custom_domain = true },
  { pattern = "udemy.com.afrcloud.site", custom_domain = true },
  { pattern = "ruangguru.com.afrcloud.site", custom_domain = true },
  { pattern = "data.mt.afrcloud.site", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "a05083cee0c54935b38878aa76e2fff3"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "bbbbbbbb-cccc-4ddd-eeee-ffffffffffff"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/AFRcloud/Inconigto-Mode/refs/heads/master/web/converter.html"
