
  { pattern = "afrcloud.site", custom_domain = true },
  { pattern = "ava.game.naver.com.afrcloud.site", custom_domain = true },
  { pattern = "quiz.int.vidio.com.afrcloud.site", custom_domain = true },
  { pattern = "graph.instagram.com.afrcloud.site", custom_domain = true },
  { pattern = "zaintest.vuclip.com.afrcloud.site", custom_domain = true },
  { pattern = "support.zoom.us.afrcloud.site", custom_domain = true },
  { pattern = "cache.netflix.com.afrcloud.site", custom_domain = true },
]
