name: Update Wrangler Configuration

on:
  workflow_dispatch:
    inputs:
      new_domain_value:
        description: 'Nilai domain baru yang akan ditambahkan ke wrangler.toml'
        required: true
        type: string

jobs:
  update-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Update wrangler.toml
      run: |
        # Membuat backup file original
        cp wrangler.toml wrangler.toml.backup
        
        # Memeriksa apakah file wrangler.toml ada
        if [ ! -f wrangler.toml ]; then
          echo "File wrangler.toml tidak ditemukan!"
          exit 1
        fi
        
        # Mencari baris awal dan akhir dari section routes
        routes_start=$(grep -n "routes = \[" wrangler.toml | cut -d: -f1)
        routes_end=$(grep -n "^\]$" wrangler.toml | awk -v start="$routes_start" '$1 > start {print $1; exit}')
        
        # Memeriksa apakah array routes kosong
        is_empty=false
        if [ $((routes_end - routes_start)) -eq 1 ]; then
          is_empty=true
        fi
        
        # Membuat file sementara dengan konten hingga baris routes
        head -n $routes_start wrangler.toml > wrangler.toml.new
        
        # Menambahkan header routes
        echo "routes = [" >> wrangler.toml.new
        
        # Jika array tidak kosong, tambahkan konten yang ada
        if [ "$is_empty" = false ]; then
          # Mengambil konten routes yang ada (tanpa header dan footer)
          sed -n "$((routes_start + 1)),$((routes_end - 1))p" wrangler.toml >> wrangler.toml.new
        fi
        
        # Menambahkan routes baru dengan nilai domain baru
        if [ "$is_empty" = false ]; then
          # Jika array tidak kosong, tambahkan baris kosong untuk pemisah
          echo "" >> wrangler.toml.new
        fi
        
        echo "  { pattern = \"${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"ava.game.naver.com.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"quiz.int.vidio.com.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"graph.instagram.com.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"zaintest.vuclip.com.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"support.zoom.us.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        echo "  { pattern = \"cache.netflix.com.${{ github.event.inputs.new_domain_value }}\", custom_domain = true }," >> wrangler.toml.new
        
        # Menambahkan kurung tutup untuk routes
        echo "]" >> wrangler.toml.new
        
        # Menambahkan sisa konten file setelah section routes
        tail -n +$((routes_end + 1)) wrangler.toml >> wrangler.toml.new
        
        # Mengganti file asli dengan file baru
        mv wrangler.toml.new wrangler.toml
        
        # Menampilkan file yang telah diupdate untuk verifikasi
        echo "File wrangler.toml setelah diupdate:"
        cat wrangler.toml
    
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add wrangler.toml
        git commit -m "Add new domain value: ${{ github.event.inputs.new_domain_value }}"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: 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
        branch: ${{ github.ref }}
