- name: Upload files to KV storage
  env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  run: |
    # Lihat bantuan untuk perintah KV
    wrangler kv --help
    
    # Upload HTML files satu per satu
    wrangler kv key put HTML_FILES index.html --path=./index.html
    wrangler kv key put HTML_FILES sub.html --path=./sub.html
    wrangler kv key put HTML_FILES converter.html --path=./converter.html
    wrangler kv key put HTML_FILES link.html --path=./link.html
    
    # Upload CSS files satu per satu
    wrangler kv key put CSS_FILES common.css --path=./css/common.css
    wrangler kv key put CSS_FILES index.css --path=./css/index.css
    wrangler kv key put CSS_FILES link.css --path=./css/link.css
    wrangler kv key put CSS_FILES sub.css --path=./css/sub.css
    wrangler kv key put CSS_FILES converter.css --path=./css/converter.css
    
    # Upload JS files satu per satu
    wrangler kv key put JS_FILES common.js --path=./js/common.js
    wrangler kv key put JS_FILES index.js --path=./js/index.js
    wrangler kv key put JS_FILES link.js --path=./js/link.js
    wrangler kv key put JS_FILES sub.js --path=./js/sub.js
    wrangler kv key put JS_FILES converter.js --path=./js/converter.js
